### ISSUE TITLE
backwards compatibility issue 1.1.0  - 1.2.1

### ISSUE THREAD

**Issue by matheboy** [nfrechette/acl#226]
I came across the issue that my test clip compressed with acl 1.1.0 and uniformly_sampled cannot be read in acl 1.2.1.  for example 'clip_header.sample_rate' is not read properly for me.
I am still trying to grasp what is happening and get some repro data I can share... 
but maybe someone can save me the work and know already whats going on?
thanks in advance

*edited: repro with sjson and bin files here
[acl_samples.zip](https://github.com/nfrechette/acl/files/3730029/acl_samples.zip)

```
		std::ifstream input_file_stream(options.input_filename, std::ios_base::in | std::ios_base::binary);
		if (input_file_stream.is_open())
		{
			// at this point we read the file
			input_file_stream.seekg(0, input_file_stream.end);
			const size_t buffer_size = size_t(input_file_stream.tellg());
			input_file_stream.seekg(0, input_file_stream.beg);
			char* buffer = (char*)allocator.allocate(buffer_size, alignof(CompressedClip));
			input_file_stream.read(buffer, buffer_size);
			// as compressed clip
			const CompressedClip* compressed_clip = reinterpret_cast<const CompressedClip*>(buffer);
			ACL_ASSERT(compressed_clip->is_valid(true).empty(), "Compressed clip is invalid");
			// now read header
			const ClipHeader& clip_header = get_clip_header(*compressed_clip);

			const uint32_t num_samples = clip_header.num_samples;

			Transform_32* lossy_pose_transforms = allocate_type_array<Transform_32>(allocator, clip_header.num_bones);

			const float clip_duration = calculate_duration(clip_header.num_samples, clip_header.sample_rate);
```
clip_header.sample_rate=30 //on version 1.1.0
clip_header.sample_rate=4.204e-44#DEN //on version 1.2.1

**Comment by nfrechette** [comment]
That is correct, ACL v1.2 changed how the sample rate is stored from an integer to a float and as such the binary format changed and is not compatible. In general, the binary format is not guaranteed to be backwards compatible between major and minor releases (but guaranteed for patch releases).

ACL is not meant as a long term storage format (yet), unlike JPG and PNG for example. It is meant as a runtime format and it is necessary to sometime recompress when you update the library. Most game engines do not store compressed clips in persistent storage like version control and instead just cache the compression result on demand. If you call `is_valid()` on the `CompressedClip` it should return false because the version changed. As such, it cannot be used and it must be recompressed.

I understand that this is a significant torn and I hope to get it fixed next year. I am finishing up v1.3 and will release v2.0 shortly after with very minimal changes (details will come soon). Once that is done, my focus will be on standardizing ACL to make it suitable for long term storage with proper backwards compatibility support. Note that v1.3 will also require recompression and will not be compatible with data from v1.2.

**Comment by matheboy** [comment]
All clear thanks @nfrechette

**Comment by nfrechette** [comment]
To clarify a bit, updating from v1.3 to v2.0 will be trivial: the only breaking change will be the requirement of a new include path for [Realtime Math]() which will be a required runtime dependency. The APIs won't change and v2.0 will be binary compatible/identical to v1.3. Changes will otherwise be minor and consist of cleanup. Tasks currently scheduled for v2.0 will be pushed to v3.0 for the most part.

Going forward, I hope that v2.1 can be the first version to support backwards compatibility and I hope to keep it binary compatible with v2.0 (and thus v1.3) as well. All of this will be detailed in time in blog posts and the documentation. One motivating factor for standardizing and backwards compatibility support is that I will be creating a glTF extension and a webassembly version of ACL to natively support the web. Later, FBX and Alembic extensions will be written as well.

The long term vision for ACL is to be able to compress directly in your DDC (Maya, 3dsmax, etc), view the results there, and save the compressed file standalone or as part of your FBX, etc. On the game engine side, post processing will be supported for LOD reordering and endian swapping, things of that nature that do not require full recompression and access to the raw data. ACL will become just like JPG or other video/image compression formats.
