### ISSUE TITLE
Does ACL take into account loss of precision between frames for additive animations?

### ISSUE THREAD

**Issue by Oinkium** [nfrechette/acl#499]
Making animations additive can introduce a loss of precision between frames, even if the keyframes are all stored at full precision. 

Indeed, if we are at prop `t` between frames `frame0` and `frame1`, then the 'original' animation (before being made additive) has the pose

`Interpolate( additive( frame0 ) * base( frame0 ), additive( frame1 ) * base( frame1 ), t )`, 

whereas when the game runtime calculates the additive and base animations and superposes them it will calculate

`Interpolate( additive( frame0 ), additive( frame1 ), t ) * Interpolate( base( frame0 ), base( frame1 ), t )`

In practice, these errors are small if the frame rate is high enough, and can be made smaller still by supersampling the additive animation. Does ACL take this into account at all? Will it ever retain a higher bitrate in order to make sure that the error between frames is always below the threshold?

**Comment by nfrechette** [comment]
Hello,

ACL does take into account the additive base when compressing additive animations. When provided during compression, the error is measured when the additive is on the base (as opposed to measuring in additive space). However, ACL measures the error on the keyframes as provided during compression. We do not currently re-sample animations nor do we support measuring the error at higher sampling rates (e.g. in between raw keyframes).

For normal 30/60 FPS sampling rates, visual fidelity is typically very close to raw with default settings (0.1mm precision). Applying an additive won't introduce much more error than you would get from other operations such as blending, etc. ACL doesn't know what happens with the pose once it is produced and as such it does its best at reproducing the original keyframes.

If you view animations at much higher sampling rates, perhaps in slow motion moments (e.g. 240 FPS displayed at 30 FPS),  then any loss in precision from interpolation might become much more visible. In cases like this, I would recommend that you export your animations at a higher sampling rate. Even with a higher sampling rate and more keyframes, the animation should compress reasonably well since neighbouring keyframes will be much more similar as they are closer in time. If you do not increase the sampling rate of the raw data, the visual fidelity will suffer with any codec that doesn't use spline based interpolation (which ACL doesn't support).

Allowing ACL to measure the error at a higher sampling rate than the animation could be supported but I'm not sure if it would provide enough benefits to justify the added complexity. If the sampling rate of the animation is too low, even with the raw data visual fidelity could be poor, and ACL won't be able to do better than what the raw data provides. In particular, for ACL to know what the raw data should look like in between keyframes, it would need to support the original raw data curves and there are too many formats to support (bezier, catmul-romm, etc). If it turns out that the curve passes too far from where linear interpolation lies, ACL may not be able to reach the desired precision even retaining raw data, significantly hurting the compression ratio with little to show for it. We would have to support curves during decompression as well for it to be viable. Most practical curves require at least 4 values to be unpacked to reconstruct the desired value which would slow down decompression quite a bit. ACL tries to strike a good balance between decompression performance, memory footprint, and visual fidelity.

Do you have a specific example where you see interpolation degrading visual fidelity significantly with ACL (with or without additive)?

**Comment by Oinkium** [comment]
Hi, 

I was more hoping that ACL might help to fix a long-standing issue with how our engine handles motion extraction.

Motion extraction (which can be thought of as making the root joint additive to the motion track) suffers from a loss of precision between keyframes if we interpolate the motion and the animation separately and then combine them (vs interpolating before extracting the motion). For this reason, our engine performs motion extraction at runtime, even though doing it in the animation compiler would be more convenient.

I investigated this and found that for most clips the error is in fact zero or very small. Which got me thinking - if the error introduced in this way is smaller than the error threshold we have already said we're OK with for ACL compression, then it seems silly to jump through a lot of hoops in order to avoid it. So could we perform motion extraction in the compiler and insert frames in the rare case that the introduced error is greater than our stated error threshold?

One thing I tried is manually resampling the animation to a much higher frame rate (via interpolation) before extracting motion, in the hope that in the majority of cases ACL will be able to compress it very easily and we won't get a large increase in memory usage. Unfortunately, that didn't seem to be the case - resampling from 30fps to 240fps increased the overall memory usage post-compression by 3-4x.

**Comment by nfrechette** [comment]
That's a rather unusual issue. If you prefer, feel free to email me at zeno490@gmail.com if you'd rather keep the discussion private.

Generally speaking, interpolation errors come in two forms:
* If there aren't enough samples, linear interpolation can struggle to approximate fast moving curves
* If rotations are far apart, spherical interpolation (aka slerp) may yield a better result as linear interpolation is not guaranteed to pick the best result (slerp is not yet supported by ACL as no one has had a need for it yet)

How are you measuring the error that you see? Specifically, are you using the ACL raw data to compare or do you have your own raw data format? Is that raw data using beziers or some other curve?

Are the clips that see a high error looping?

Is the error higher in high velocity moments or does it appear in slower parts as well?

Extracting motion offline is pretty common. It's typically done to ensure full fidelity but it may not necessary with ACL. ACL allows you to control per joint what precision you require (see `get_description` on the raw data tracks you populate). Typically, you want to measure the error further away for the root joint. Ordinary joints may be fine measuring at 1-3cm distance, but the root may benefit from a higher value like 100cm. The Unreal Engine plugin does this for the root joint and various others that match a list of strings (e.g. hand, IK, weapon, etc).

Inserting frames is a bit more tricky. ACL expects the data to be uniformly sampled with a fixed sample rate throughout each clip. The only way to add keyframes is to increase your sampling rate. You can use any floating point value for your sampling rate (e.g. 24.6 FPS would work). That being said, 60 FPS is usually plenty for 99.99% of animations and possibly overkill for many. Going from 30FPS to 240FPS is a 8x increase in the number of keyframes, so if the compressed footprint only increases by 3-4x, that's not too bad :)

Aside from that, historically I've spent a LOT of time hunting down subtle interpolation discrepancies in various places in ACL. It took many years to iron out all the kinks and make sure everything was consistent. Here are some lessons I learned along the way that may help you in your hunt.

How the error is measure is really important. Not only must the same keyframes be selected but the interpolation alpha must be identical as well. The interpolation can vary from one place to another even if the same sampling time is used for various reasons. Code generation plays a part. You have to be consistent in how you calculate the value in using divisions at the same place. I also found that I had to disable fastmath to ensure that the generated assembly was consistent. With fastmath enabled, the same inlined code can yield different sequences of instructions which can slightly alter the result. Another related source of error is to make sure to use a stable lerp function. Stable lerps (and slerps) return either the source or target inputs when the interpolation alpha is 0.0 or 1.0 exactly (a binary exact source/target is returned). This means that you can't use something like `result = a + (b - a) * t` as the subtraction followed by an addition with a 1.0 `t` won't yield the binary exact `b`. You need something along the lines of `result = (1.0 - t) * a + t * b`. For those reasons, I recommend using the ACL provided functions to measure the error between the raw and compressed ACL data. Rolling out your own function is likely to give different results.

**Comment by nfrechette** [comment]
Have you made any progress on your issue?
Have you managed to narrow down the issue to be inside/outside ACL?

**Comment by Oinkium** [comment]
Hi, 

The issue is definitely outside ACL. In the end, I think we will stick with motion extraction at runtime. It's not particularly costly and can be useful in some situations.

Thanks for your help and all the info. If I decide to investigate this again in the future then I'll have a look at trying to match the ACL functions more exactly when supersampling.
