### ISSUE TITLE
Add support for GCC 6 and 7 on Linux

### ISSUE THREAD

**Issue by nfrechette** [nfrechette/acl#63]
Once the unit tests are extended and in place, adding support for this should be trivial and simply require to add them to travis.

**Comment by janisozaur** [comment]
Whoa, there are quite a few jobs you spawn on Travis, as of 228e5d there are 20(!) of them and 8 of them are on OS X. Travis is a public, shared service offered for free to open source projects and they are constantly starved for OS X workers, see https://www.traviscistatus.com/#month

Unless you actually ship all the built artifacts, I see no justification to having that many and especially not extending them by 8 more, as this issue seems to suggest.

You should be fine with half of the jobs or even less, test whatever highest and lowest compilers you support, there will be little to no difference between `release` and `debug` mode (bar occasional `final` suggestion or `nullptr` check), and seeing how infrastructure set up takes about 10x the time of build + test[1], you can consider re-use of the build jobs for `x86` and `x86-64` (which btw you could fix the name of) or `debug` and `release`.

I have also tested GCC6 or 7, but that resulted in package install taking much, much longer than they do right now. That should probably be less of an issue once Xenial images become available. There are some alternatives like using pre-built docker images that turn out to be faster than installing packages on the provisioned system.

[1] https://travis-ci.org/nfrechette/acl/jobs/325311331, 148s for packages installation, 16s for build + test runs

**Comment by nfrechette** [comment]
Yes, the number of jobs is a bit high at the moment and travis seems unusually unstable with jobs often timing out when updating packages or installing them. Merging the jobs for debug/release is a good idea and with appveyor, we could merge x86/x64 as well. OS X jobs could be merged in a similar fashion.

Though at the end of the day, this project doesn't have that high a velocity. New builds aren't kicked off very often. I do think its important to test debug/release and x86/x64 not because the they might be used but because it is cheap to test them and can sometimes highlight compilation errors. I work primarily on windows with vs2015, I rarely if ever build and test gcc5 in debug or osx in debug.

I've created issue #64 to merge the jobs in the next milestone as I'm ready to close down the current release soon-ish. Feel free to tackle this sooner if you'd like :)
